window.SMN_CURATED = [
  "paracetamol",
  "metformin",
  "amlodipine",
  "losartan",
  "telmisartan",
  "enalapril",
  "ramipril",
  "atorvastatin",
  "rosuvastatin",
  "omeprazole",
  "esomeprazole",
  "pantoprazole",
  "levothyroxine",
  "furosemide",
  "spironolactone",
  "hydrochlorothiazide",
  "bisoprolol",
  "metoprolol",
  "carvedilol",
  "aspirin",
  "clopidogrel",
  "warfarin",
  "rivaroxaban",
  "amoxicillin",
  "amoxicillin + clavulanic acid",
  "azithromycin",
  "doxycycline",
  "ciprofloxacin",
  "cefuroxime",
  "ceftriaxone",
  "cetirizine",
  "loratadine",
  "fexofenadine",
  "montelukast",
  "salbutamol",
  "budesonide",
  "prednisolone",
  "dexamethasone",
  "diclofenac",
  "ibuprofen",
  "naproxen",
  "pregabalin",
  "gabapentin",
  "sertraline",
  "escitalopram",
  "ferrous fumarate",
  "calcium carbonate + vitamin d3",
  "vitamin d3",
  "zinc"
];
